two types of errors:
- compile errors, java will tell you something will break later
- runtime errors, happen during execution of program

stupid ways to deal with runtime errors
- if-else statements to ignore bad input

custom errors
- conventeion to include the `throws Exception` above, not enforced all the time but sometimes is required so might as well always use it
```java
public static int quotient(int a, int b) throws ArithmeticException{  
    if (b != 0) {  
        return a/b;  
    }  
    else {  
        throw new ArithmeticException("Divisor cannot be 0");  
    }  
}
```

try-catch block
- ArithmeticException is a class and .getMessage is a method available to that class
```java
try {  
    int n1 = input.nextInt();  
    int n2 = input.nextInt();  
    int result = quotient(n1, n2);  
    System.out.printf("%d / %d = %d", n1, n2, result);  
}  
catch(ArithmeticException ex){  
    System.out.printf("Exception caught: %s", ex.getMessage());  
}  
catch(InputMismatchException ex){  
    System.out.println("non-int input detected");  
}
```

can create general exception handlers
- Exception is the root class to all exception classes
- this means that you have to have specific catch blocks before the Exception class is called (inheritance matters here)
```java
try {  
    int n1 = input.nextInt();  
    int n2 = input.nextInt();  
    int result = quotient(n1, n2);  
    System.out.printf("%d / %d = %d", n1, n2, result);  
}  
catch(InputMismatchException ex){
	System.out.println("Non-int input was detected");
}
catch(Exception ex){  
    System.out.printf("Exception caught: %s\n", ex.getMessage());  
}
```

finally block
- always executed no matter what
- why is it useful?
	- can put code after a return statement that will happen always 
	- not really used that much, Seth hasn't heard of people ever using these trick lol
	- cleanup actions for things like databases, closing files, etc
```java
try {  
    int n1 = input.nextInt();  
    int n2 = input.nextInt();  
    int result = quotient(n1, n2);  
    System.out.printf("%d / %d = %d", n1, n2, result);  
}  
catch(Exception ex){  
    System.out.printf("Exception caught: %s\n", ex.getMessage());  
}  
finally {  
    System.out.println("This is always executed");  
}
```

using this in constructors
- checked exceptions -> make a general exception catch thingy
- in class we made a class that extended the Exception class and called it this way
```java
public class CustomExceptionsCont {  
    public static void main(String[] args) {  
        try {  
            Circle c1 = new Circle(1);  
            Circle c2 = new Circle(0);  
            Circle c3 = new Circle(4);  
        }  
        catch (InvalidRadiusException ex) {  
            System.out.printf("Cannot make circle with radius: %f", ex.getRadius());  
        }  
    }  
}  
class InvalidRadiusException extends Exception {  
    private double radius;  
    public InvalidRadiusException(double radius){  
        this.radius = radius;  
    }  
    public double getRadius() {  
        return radius;  
    }  
}  
class Circle {  
    private double radius;  
    public Circle( double radius) throws InvalidRadiusException{  
        if (radius > 0){  
            this.radius = radius;  
        }  
        else {  
            // checked exception  
            throw new InvalidRadiusException(radius);  
        }  
    }  
    public double getRadius(){  
        return radius;  
    }  
    public double getArea(){  
        return Math.PI * this.radius * this.radius;  
    }  
}
```